logging:
  file:
    name: ${java.io.tmpdir}/${spring.application.name}.log
    max-size: 50MB
  level:
    org.apache.pdfbox.io.ScratchFileBuffer: WARN

management:
  endpoints:
    web.exposure.include: "*"

flows.runner:
  cron: "0 0/30 * * * ?"

alcohol.retriever:
  cron: "0 0/5 * * * ?"

image.verifier:
  cron: "0 0/5 * * * ?"

kaufland:
  base.url: https://www.kaufland.bg/aktualni-predlozheniya/ot-ponedelnik.html

lidl:
  base.url: https://www.lidl.bg

fantastico:
  url: https://www.fantastico.bg/special-offers

billa:
  url: https://ssbbilla.site/weekly

tmarket:
  base.url: https://tmarketonline.bg/

google:
  image.search:
    url: https://www.google.bg/search?source=lnms&tbm=isch
  custom.search:
    url: https://www.googleapis.com/customsearch/v1?key=${GOOGLE_API_KEY:}&cx=0b1305ac3733516ec&searchType=image

cloudinary:
  cloud.name: dhf90uh66
  api:
    key: 131315184557651
    secret: ${CLOUDINARY_API_SECRET:}

spring:
  application.name: sofia-supermarkets-api
  jpa:
    hibernate.ddl-auto: none
  datasource:
    hikari:
      maximum-pool-size: 2
    url: "jdbc:postgresql://queenie.db.elephantsql.com:5432/nwshtxej"
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}
  jackson:
    serialization:
      write-dates-as-timestamps: false